name: SMSML_CalebAnthony
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy>=1.26.4
    - pandas>=2.2.0
    - tensorflow>=2.16.1
    - scikit-learn>=1.4.0
    - joblib>=1.3.2
    - mlflow==2.19.0
    - dagshub
    - matplotlib>=3.8.0
    - seaborn>=0.13.0
    - tf-keras>=2.16.0
