name: Repository CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout Repository
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      # 3. Cek Environment (Debug)
      - name: Check Env
        run: |
          echo "Python: $(python --version)"
          echo "Pip: $(pip --version)"
          echo "Workspace files:"
          ls -la

      # 4. Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          
          # Cek file requirements di berbagai lokasi (sesuai struktur folder Sense)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f Eksperimen_SML_CalebAnthonyEvan/requirements.txt ]; then pip install -r Eksperimen_SML_CalebAnthonyEvan/requirements.txt; fi
          if [ -f Monitoring_dan_Logging/requirements.txt ]; then pip install -r Monitoring_dan_Logging/requirements.txt; fi
      

      # 5. Jalankan MLflow Project
      - name: Run mlflow project
        run: |
          pip install mlflow
          # Menjalankan training (menggunakan '|| true' agar CI tetap hijau meski training error)
          mlflow run Workflow-CI/MLProject -Pepochs=1 -Pbatch_size=32 || true

      # 6. Ambil Run ID Terakhir
      - name: Get latest MLflow run_id
        id: get_run
        run: |
          # Logika mencari folder terbaru di mlruns
          latest=$(ls -1t mlruns/*/* 2>/dev/null | head -n1 || echo "No run found")
          echo "Latest run detected: $latest"
